### ISSUE TITLE
The Position of the snake is not updating in my debug userscript and other question

### ISSUE THREAD

**Issue by BadPlayer555** [ClitherProject/Slither.io-Protocol#84]
When you play for a while, the position from the packet will start **showing the same position** but I am still moving. (You can see my userscript at the end)

![ScreenShot](https://user-images.githubusercontent.com/24754464/38311429-c0d004a6-3851-11e8-9b68-6853a9bf874d.png)

My Questions
Question 1: How to simply fix that problem?

-- If you can answer number one then you can ignore question 2 --

Question 2: Is there anyway to measure the position by adding what will the snake will go every minisecond
for example: snake.xx = xx + Math.sin(snake.angle)  *  **the Speed

**  <-- Is there any way to know the speed, it will be a lot easier.

[link to UserScript!](https://hastebin.com/amuxecupix.js)

Please Help

**Comment by Mat2095** [comment]
I'll answer question 2 first, since it is not that difficult:
Snakes have speed, see bytes 12-13 in the s-packet. You can get the distance like this: `snake.speed * deltaTime / 4.0`, with `deltaTime` being the time since the last update in milliseconds. Then like your example: `snake.x += Math.cos(snake.ang) * distance;`.

Now let's take a look at the script:

- you might want to only print debug positions for YOUR snake:
```javascript
            if(("g"||"n"||"G"||"N") && (msg[3] << 8 | msg[4]) === snakeID){
                console.log("xPos: "+posX+" yPos: "+posY+" snakeX: "+window.snake.xx+" snakeY: "+window.snake.yy);
            }
```
- if you die and start a new game, the snakeID changes. Luckily there is a game-over-packet:
```javascript
            } else if ("v" == f) {

                haveSnakeID = false;

            } [...]
```
then the new snakeID will be set when starting the new game
- [Notice: I'm not 100% sure about this point, but it works] there is a difference between the snake-position and the snake-head-position: the snake-head is only updated when receiving some packets, the snake-position is updated on every frame for a smooth animation (inter-packet-interpolation, needs speed and more). Since your code runs on receiving packets, and not once per redraw, I'd suggest merging `headX` and `posX` into one variable.

With these changes, I was able to get somewhat-accurate results.

**Comment by BadPlayer555** [comment]
Thx Man You are the best <3 I will list you in my credit list in my new video
